import {
  Apple,
  Armchair,
  Award,
  Baby,
  Banknote,
  Bath,
  Bed,
  Beer,
  Bike,
  Bitcoin,
  Book,
  Briefcase,
  Brush,
  Building,
  Building2,
  Bus,
  Cake,
  Calculator,
  Camera,
  Car,
  CircleDollarSign,
  CircleMinus,
  CirclePlus,
  Clapperboard,
  Coffee,
  Coins,
  CreditCard,
  Cross,
  Dog,
  Droplet,
  Droplets,
  Dumbbell,
  Egg,
  Flame,
  Footprints,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Hammer,
  HandCoins,
  HandHeart,
  Handshake,
  Headphones,
  HeartPulse,
  Home,
  IndianRupee,
  Key,
  Lamp,
  Landmark,
  Laptop,
  Leaf,
  Lightbulb,
  Luggage,
  MapPin,
  Milk,
  Music,
  Package,
  PartyPopper,
  PawPrint,
  Percent,
  PieChart,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Plug,
  Receipt,
  RotateCcw,
  School,
  Scissors,
  Ship,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Soup,
  Sparkles,
  Stethoscope,
  Store,
  Syringe,
  Tag,
  Ticket,
  Train,
  TreePine,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  Utensils,
  Wallet,
  Watch,
  Wifi,
  Wine,
  Wrench,
  Zap,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

/**
 * Registry mapping stored icon names (kebab-case, matching the seeded Indian
 * defaults) to their lucide-react components. Categories persist only the icon
 * *name* string; this map resolves it back to a renderable component.
 */
export const categoryIcons = {
  apple: Apple,
  armchair: Armchair,
  award: Award,
  baby: Baby,
  banknote: Banknote,
  bath: Bath,
  bed: Bed,
  beer: Beer,
  bike: Bike,
  bitcoin: Bitcoin,
  book: Book,
  briefcase: Briefcase,
  brush: Brush,
  building: Building,
  'building-2': Building2,
  bus: Bus,
  cake: Cake,
  calculator: Calculator,
  camera: Camera,
  car: Car,
  'circle-dollar-sign': CircleDollarSign,
  'circle-minus': CircleMinus,
  'circle-plus': CirclePlus,
  clapperboard: Clapperboard,
  coffee: Coffee,
  coins: Coins,
  'credit-card': CreditCard,
  cross: Cross,
  dog: Dog,
  droplet: Droplet,
  droplets: Droplets,
  dumbbell: Dumbbell,
  egg: Egg,
  flame: Flame,
  footprints: Footprints,
  fuel: Fuel,
  gamepad: Gamepad2,
  gem: Gem,
  gift: Gift,
  glasses: Glasses,
  globe: Globe,
  'graduation-cap': GraduationCap,
  hammer: Hammer,
  'hand-coins': HandCoins,
  'hand-heart': HandHeart,
  handshake: Handshake,
  headphones: Headphones,
  'heart-pulse': HeartPulse,
  home: Home,
  'indian-rupee': IndianRupee,
  key: Key,
  lamp: Lamp,
  landmark: Landmark,
  laptop: Laptop,
  leaf: Leaf,
  lightbulb: Lightbulb,
  luggage: Luggage,
  'map-pin': MapPin,
  milk: Milk,
  music: Music,
  package: Package,
  'party-popper': PartyPopper,
  'paw-print': PawPrint,
  percent: Percent,
  'pie-chart': PieChart,
  'piggy-bank': PiggyBank,
  pill: Pill,
  pizza: Pizza,
  plane: Plane,
  plug: Plug,
  receipt: Receipt,
  'rotate-ccw': RotateCcw,
  school: School,
  scissors: Scissors,
  ship: Ship,
  'shield-check': ShieldCheck,
  shirt: Shirt,
  'shopping-bag': ShoppingBag,
  'shopping-basket': ShoppingBasket,
  'shopping-cart': ShoppingCart,
  smartphone: Smartphone,
  soup: Soup,
  sparkles: Sparkles,
  stethoscope: Stethoscope,
  store: Store,
  syringe: Syringe,
  tag: Tag,
  ticket: Ticket,
  train: Train,
  'tree-pine': TreePine,
  'trending-up': TrendingUp,
  trophy: Trophy,
  truck: Truck,
  tv: Tv,
  umbrella: Umbrella,
  utensils: Utensils,
  wallet: Wallet,
  watch: Watch,
  wifi: Wifi,
  wine: Wine,
  wrench: Wrench,
  zap: Zap,
} satisfies Record<string, LucideIcon>

export type CategoryIconName = keyof typeof categoryIcons

/** Ordered list of icon names offered in the picker. */
export const categoryIconNames = Object.keys(
  categoryIcons,
) as CategoryIconName[]

/** Fallback icon used when a category has no icon or an unknown name. */
export const fallbackCategoryIcon: LucideIcon = Tag

/** Type guard for persisted icon names before putting them into forms. */
export function isCategoryIconName(
  name: string | null | undefined,
): name is CategoryIconName {
  return Boolean(name && name in categoryIcons)
}

/** Resolve a stored icon name to a component, falling back to a generic tag. */
export function getCategoryIcon(name: string | null | undefined): LucideIcon {
  if (isCategoryIconName(name)) {
    return categoryIcons[name]
  }
  return fallbackCategoryIcon
}
